services:
  otel-collector:
    extends:
      file: docker-compose.yaml
      service: otel-collector

  dev:
    extends:
      file: docker-compose.yaml
      service: dev
    ports:
      - '8001:8000'
    depends_on:
      - otel-collector
      - mailslurper
      - oathkeeper

  kratos-migrate:
    image: oryd/kratos:v1.1.0
    environment:
      DSN: "sqlite:///home/ory/db.sqlite?_fk=true&mode=rwc"
    volumes:
      - ./auth/kratos:/home/ory
    command: -c /home/ory/kratos.yml migrate sql -e --yes
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.1.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      DSN: "sqlite:///home/ory/db.sqlite?_fk=true&mode=rwc"
      LOG_LEVEL: "trace"
    volumes:
      - ./auth/kratos:/home/ory
    command: serve -c /home/ory/kratos.yml --dev --watch-courier

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.0.0
    environment:
      KRATOS_PUBLIC_URL: "http://kratos:4433/"
      KRATOS_BROWSER_URL: "http://127.0.0.1:8000/.ory/kratos/public"
      JWKS_URL: "http://oathkeeper:4456/.well-known/jwks.json"
      SECURITY_MODE: "jwks"
    ports:
      - '3000:3000' # public
    restart: on-failure
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
    ports:
      - "8000:4455"
      - "4456:4456"
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./auth/oathkeeper:/etc/config/oathkeeper
